// Generated by CoffeeScript 1.6.2
describe("StringSplitter", function() {
  beforeEach(function() {
    var module;

    module = require('../../src/js/StringSplitter.js');
    return this.StringSplitter = new module.StringSplitter();
  });
  describe("nextPositionIn", function() {
    it("should be the same as the text length", function() {
      var i, text;

      text = 'x.x,x';
      i = this.StringSplitter.nextPositionIn(text);
      return expect(i).toBe(text.length);
    });
    it("should get the first dot", function() {
      var i, text;

      text = 'x. x,x';
      this.StringSplitter.setCharacterLimit(4);
      i = this.StringSplitter.nextPositionIn(text);
      return expect(i).toBe(text.lastIndexOf('.'));
    });
    it("should get the correct position in french", function() {
      var i, text;

      text = 'Jean VI de Portugal (en portugais : João VI de Portugal), roi de Portugal et des Algarves et roi puis empereur titulaire du Brésil, est né à Lisbonne, au Portugal, le 13 mai 1767 et décédé dans cette même ville le 10 mars 1826. Surnommé « le Clément », il règne sur le Royaume uni de Portugal, du Brésil et des Algarves de 1816 a 1822 puis sur le seul royaume de Portugal de 1822 à 1826. Grâce au traité de Rio de Janeiro de 1825, qui reconnaît l\'indépendance du Brésil, Jean VI est également proclamé empereur titulaire du Brésil, mais c\'est son fils aîné, l\'empereur Pierre I, qui est le véritable souverain du pays pendant son règne.';
      this.StringSplitter.setCharacterLimit(150);
      i = this.StringSplitter.nextPositionIn(text);
      return expect(i).toBe(text.lastIndexOf(',', 150));
    });
    return it("should get the correct position in french", function() {
      var i, text;

      text = 'Jean VI de Portugal (en portugais : Joo VI de Portugal) roi ';
      this.StringSplitter.setCharacterLimit(150);
      i = this.StringSplitter.nextPositionIn(text);
      return expect(i).toBe(text.length);
    });
  });
  return describe("stringsOf", function() {
    it("should get the correct strings", function() {
      var strings, text;

      text = 'x. x,x';
      this.StringSplitter.setCharacterLimit(4);
      strings = this.StringSplitter.stringsOf(text);
      return expect(strings).toEqual(['x.', ' x,x']);
    });
    it("should get the correct strings of french", function() {
      var strings, text;

      text = 'Jean VI de Portugal (en portugais : João VI de Portugal), roi de Portugal et des Algarves et roi puis empereur titulaire du Brésil, est né à Lisbonne, au Portugal, le 13 mai 1767 et décédé dans cette même ville le 10 mars 1826. Surnommé « le Clément », il règne sur le Royaume uni de Portugal, du Brésil et des Algarves de 1816 a 1822 puis sur le seul royaume de Portugal de 1822 à 1826. Grâce au traité de Rio de Janeiro de 1825, qui reconnaît l\'indépendance du Brésil, Jean VI est également proclamé empereur titulaire du Brésil, mais c\'est son fils aîné, l\'empereur Pierre I, qui est le véritable souverain du pays pendant son règne.';
      this.StringSplitter.setCharacterLimit(150);
      strings = this.StringSplitter.stringsOf(text);
      return expect(strings).toEqual(['Jean VI de Portugal (en portugais : João VI de Portugal), roi de Portugal et des Algarves et roi puis empereur titulaire du Brésil, est né à Lisbonne,', ' au Portugal, le 13 mai 1767 et décédé dans cette même ville le 10 mars 1826.', ' Surnommé « le Clément », il règne sur le Royaume uni de Portugal,', ' du Brésil et des Algarves de 1816 a 1822 puis sur le seul royaume de Portugal de 1822 à 1826.', ' Grâce au traité de Rio de Janeiro de 1825, qui reconnaît l\'indépendance du Brésil, Jean VI est également proclamé empereur titulaire du Brésil,', ' mais c\'est son fils aîné, l\'empereur Pierre I, qui est le véritable souverain du pays pendant son règne.']);
    });
    return it("should get the correct strings of french again", function() {
      var strings, text;

      text = "Incapable de résister à l'attaque du général Junot, le prince Jean prend la décision de fuir son royaume et de transférer la cour et le gouvernement au Brésil, qui est alors la plus prospère des colonies portugaises. Après plusieurs semaines de tribulations, la famille royale et les 500 à 15 000 personnes qui l'accompagnent (selon les sources) s'installent donc à Rio de Janeiro le 7 mars 1808. En compagnie de ses conseillers, le régent met rapidement en place une série de réformes qui ouvrent le Brésil au commerce international et le dotent d'institutions stables et modernes.";
      this.StringSplitter.setCharacterLimit(150);
      strings = this.StringSplitter.stringsOf(text);
      return expect(strings).toEqual(['Incapable de résister à l\'attaque du général Junot,', ' le prince Jean prend la décision de fuir son royaume et de transférer la cour et le gouvernement au Brésil,', ' qui est alors la plus prospère des colonies portugaises.', ' Après plusieurs semaines de tribulations,', ' la famille royale et les 500 à 15 000 personnes qui l\'accompagnent (selon les sources) s\'installent donc à Rio de Janeiro le 7 mars 1808.', ' En compagnie de ses conseillers,', ' le régent met rapidement en place une série de réformes qui ouvrent le Brésil au commerce international et le dotent d\'institutions stables et ', 'modernes.']);
    });
  });
});
