// Generated by CoffeeScript 1.6.2
var Split, split, text;

String.prototype.trim = function() {
  return this.replace(/^\s+|\s+$/g, '');
};

exports.Split = Split = (function() {
  Split.prototype.FRMARK = '...';

  function Split(StringSplitter) {
    var module;

    if (!StringSplitter) {
      module = require("./StringSplitter.js").StringSplitter;
      StringSplitter = new module();
    }
    this.splitter = StringSplitter;
  }

  Split.prototype.run = function(text) {
    var isFr, string, strings, _i, _len, _results;

    isFr = false;
    if (text.indexOf(this.FRMARK) === 0) {
      text = text.substring(this.FRMARK.length);
      isFr = true;
    }
    strings = this.splitter.stringsOf(text);
    _results = [];
    for (_i = 0, _len = strings.length; _i < _len; _i++) {
      string = strings[_i];
      if (isFr) {
        string = "" + this.FRMARK + "-" + string;
      }
      _results.push(process.stdout.write(string + "\n"));
    }
    return _results;
  };

  return Split;

})();

process.argv.shift();

process.argv.shift();

text = process.argv.join(" ");

if (text !== 'test') {
  split = new exports.Split();
  split.run(text);
  process.exit(0);
}
