// Generated by CoffeeScript 1.6.2
var StringSplitter;

exports.StringSplitter = StringSplitter = (function() {
  var DEFAULT_CHARACTERS_LIMIT, DEFAULT_SPLITTERS;

  DEFAULT_SPLITTERS = [". ", ". ", ", ", ",", ";", ":", "|", " ", ".", ".", "،", "، "];

  DEFAULT_CHARACTERS_LIMIT = 100;

  function StringSplitter(characterLimit, splitters) {
    this.characterLimit = characterLimit != null ? characterLimit : DEFAULT_CHARACTERS_LIMIT;
    this.splitters = splitters != null ? splitters : DEFAULT_SPLITTERS;
  }

  StringSplitter.prototype.nextPositionIn = function(text) {
    var i, iteration;

    i = text.length;
    iteration = 0;
    if (i > this.characterLimit) {
      i = text.lastIndexOf(this.splitters[iteration], this.characterLimit);
      while (i < 1 && iteration < this.splitters.length) {
        iteration = iteration + 1;
        i = text.lastIndexOf(this.splitters[iteration], this.characterLimit);
      }
      if (i < 1) {
        return i = text.length;
      } else {
        return i;
      }
    } else {
      return i;
    }
  };

  StringSplitter.prototype.stringsOf = function(text) {
    var i, list;

    i = 0;
    list = [];
    while (text.length > this.characterLimit) {
      i = this.nextPositionIn(text);
      list.push(text.substring(0, i + 1));
      text = text.substring(i + 1);
    }
    list.push(text);
    return list;
  };

  StringSplitter.prototype.setCharacterLimit = function(limit) {
    return this.characterLimit = limit;
  };

  return StringSplitter;

})();
