// Generated by CoffeeScript 1.3.3
(function() {
  var cache, fs, home, link_name, msg, path, removables, sender, skype_pattern;

  fs = require('fs');

  path = require('path');

  sender = 'READER_LAST_SENDER';

  home = path.relative('~');

  skype_pattern = /(\w+)\s\w+:\s(.+)/;

  removables = [/:p/, /:P/, /:d/, /:\)/, /:\(/, /:D/, /\s+/];

  msg = "" + (path.join(home, ".skypetmp", "msg_")) + "T.txt";

  link_name = " LINK ";

  cache = {
    '/etc': '/etc/private'
  };

  fs.realpath('/home', cache, function(err, resolvedPath) {
    console.log(resolvedPath);
    console.log(home);
    return console.log(msg);
  });

}).call(this);
